### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by descendingnerdliness** [rpmohn/a4#13]
When I run a4, it produces 
"a4: error while loading shared libraries: libtickit.so.3: cannot open shared object file: No such file or directory."
However, the file is in "/usr/local/lib".
What did I miss?

**Comment by rpmohn** [comment]
Run `sudo lddconfig` and that should fix it. I realized just this week that was needed after building the libraries and added it to the install page. I'll add it to the README.md now, too. You can confirm that it fixed it by running `ldd` on the a4 executable file and make sure it finds all the libraries.

**Comment by descendingnerdliness** [comment]
I have been playing with linux for a long time and I'm sure I remember lddconfig, but could not find it. I did find ldconfig and that seems to have solved the problem.
Thank you, sir.
