### ISSUE TITLE
Please test building this tarball pre-release!

### ISSUE THREAD

**Issue by rpmohn** [rpmohn/a4#14]
In an effort to make installation of a4 much simpler, this puts in all needed prerequisite library source code under the lib/ subdirectory. This also improves flexibility in the event that I want to use a new library feature that isn't yet in the mainstream package managers. 

For a full test, you can uninstall all of the unibilium, libtermkey, libtickit, and libvterm libraries on your system, even though that shouldn't be required.

@MaxGyver83 @littlewing7 and anyone else who can test this for me, please post your results here. Thank you! -Ross 

[a4-v0.2.2-libs.tar.gz](https://github.com/rpmohn/a4/files/12136914/a4-v0.2.2-libs.tar.gz)

**Comment by MaxGyver83** [comment]
I could install a4 from this tarball in an Ubuntu 20.04 Docker container (with none of those libraries installed).

**Comment by littlewing7** [comment]
Hi Ross, 

I build on kali-linux without libs: 

`$ dpkg -l | grep -P "unibilium|libtermkey|libvterm|libtickit"
`
`
[Tue Aug 01 17:39:10] mmax@sidbox1 /var/tmp/a4-prerelease/untar/a4-v0.2.2-libs
`
`$ tar -xvf ../a4-v0.2.2-libs.tar.gz
a4-v0.2.2-libs/
a4-v0.2.2-libs/cleanlibs.sh
a4-v0.2.2-libs/layouts.c
a4-v0.2.2-libs/utilities.c
a4-v0.2.2-libs/vt.c
...`

'''
![image](https://github.com/rpmohn/a4/assets/24845072/e743e307-76c9-4998-99ce-c3330c77c2b6)
'''
![image](https://github.com/rpmohn/a4/assets/24845072/d967e8a0-a6fd-4e11-b7f3-0b17043637cd)
'''
![image](https://github.com/rpmohn/a4/assets/24845072/2cdc7fb2-d9ff-42a3-9ea2-bae9f19f0b0f)


All work fine!! 

Max

**Comment by rpmohn** [comment]
Closing this with release of v0.2.3.
